---
title: "nwt_pikas_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{nwt_pikas_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, fig.width = 5, dpi = 100}
library(alohaal)
library(tidyverse)
library(ggmap)
library(sf)
```

```{r}
# Explain pikas and NWT
# start with explaining importance of geographical plots
# Explain sf
# do a simple sf demonstration with colorado
# explain ggmap
# do a simple ggmap demonstration
# combine them and analyze findings


ggplot() +
  geom_point(data = nwt_pikas, aes(
    x = easting,
    y = northing,
    color = local_site,
    alpha = 0.4
  ))


nwt_coords <-
  nwt_pikas %>% filter(!is.na(easting) &
                         !is.na(northing)) #%>% mutate(year = as.integer(year))
test <- st_as_sf(nwt_coords, coords = c("easting", "northing"))
ggplot(data = test) + geom_sf(aes(color = local_site, shape = local_site), alpha = 0.3) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
  theme_minimal() +
  labs(title = "Location of Pika Samples")

ggplot(data = nwt_pikas) +
  stat_density2d(aes(fill = ..level.., x = easting, y = northing), alpha = .5,
                 geom = "polygon") + 
  scale_fill_viridis_c()  + 
  theme_minimal() +
  labs(title = "Location of Pika Samples")

nwt <- c(left = -106, bottom = 39.8433, right = -105, top = 40.2339)

pikas_location <-c(left = -105.65, bottom = 40, right = -105.55, top = 40.12)

ggmap(get_stamenmap(nwt, zoom = 11, maptype = "terrain"))
test$geometry <- st_set_crs(test$geometry, "+proj=utm +zone=13 +datum=WGS84")
test$s.sf.gcs <- st_transform(test$geometry, "+proj=longlat +datum=WGS84")
test$geometry <- test$s.sf.gcs
ggmap(get_stamenmap(pikas_location, zoom = 11, maptype = "terrain")) + # geom_point(data = test, aes(
# x = easting,
# y = northing,
#  color = local_site,
# alpha = 1)) 
#geom_sf(data = test$geometry, alpha = 0.3, inherit.aes = FALSE)
#geom_sf(data = test, aes(color = local_site, shape = local_site), alpha = 0.3) +
#  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
##  scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
#  theme_minimal() +
#  labs(title = "Location of Pika Samples")

 geom_sf(data = test, inherit.aes = FALSE, aes(color = local_site, shape = local_site), alpha = 0.3) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  #scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
  theme_minimal() +
  labs(title = "Location of Pika Samples")

```

```{r}
nwt_pikas %>% count(year) %>% ggplot(aes(x = year, y = n)) +
  geom_bar(stat = "identity")
```
```{r temps, fig.width = 5, dpi = 100}
temps <- ggplot(data = nwt_pikas %>% filter(!is.na(sex)), aes(x = rectal_temp, y = weight)) + geom_point(aes(color = sex, shape = sex), alpha = 0.8) +
  theme_minimal() +
  labs(title = "Rectal Temperatures and Weights of Pikas",
       y = "Weight", x = "Rectal Temperature")
temps
```

```{r weights_sex, fig.width = 5, dpi = 100}
weights_sex <- ggplot(data = nwt_pikas %>% filter(!is.na(sex)), aes(x = sex, y = weight)) + geom_boxplot(aes(color = sex, shape = sex), alpha = 0.8, width = 0.5) +
  theme_minimal() +
  labs(title = "Weights of Male and Female Pikas",
       y = "Weight", x = "Sex")
weights_sex
```

```{r weights_sites, fig.width = 5, dpi = 100}
weights_sites <- ggplot(data = nwt_pikas, aes(x = local_site, y = weight)) + geom_boxplot(aes(color = local_site, shape = local_site), alpha = 0.8, width = 0.5) +
     theme_minimal() +
     labs(title = "Weights of Pikas by Site",
          y = "Weight (grams)", x = "Sites")
weights_sites
```

```{r weights_stage, fig.width = 5, dpi = 100}
weights_stage <- ggplot(data = nwt_pikas %>% filter(!is.na(stage)), aes(x = stage, y = weight)) + geom_boxplot(aes(color = stage, shape = stage), alpha = 0.8, width = 0.5) +
     theme_minimal() +
     labs(title = "Weights of Pikas by Stage",
          y = "Weight", x = "Stage")
weights_stage
```
